name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aiken-lang/setup-aiken@v0.1.0
        with:
          version: v1.0.26-alpha

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './agora-expansion/package-lock.json'

      - name: Install dependencies
        working-directory: ./agora-expansion
        run: npm install

      - name: Build TypeScript
        working-directory: ./agora-expansion
        run: npm run build

      - name: Run tests
        working-directory: ./agora-expansion
        run: npm test

      - run: aiken fmt --check
        working-directory: ./agora-expansion
      - run: aiken check -D
        working-directory: ./agora-expansion
      - run: aiken build
        working-directory: ./agora-expansion
